---
engines:
  duplication:
    enabled: true
    exclude_fingerprints:
    - 75482e36b2a61b803d0f2bd1b2a1850c
    - 631e101a0a1ea6fe8122daaf91d6532d
    - 6cfac5dbfb935ae391ba6b266238ccde
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- tests/
- templates/views/
- "README.md"
- "LICENSE.md"
- "changelog.md"
