---
branches:
  only:
    - master
services:
  - mongodb
language: node_js
node_js:
  - "6.9.2"
sudo: true
addons:
  apt:
    packages:
    - nginx
cache:
  directories:
    - node_modules
before_install:
  - npm config set spin false
  - npm install -g ember-cli@2.9.1
  - npm install -g bower
  - npm install -g forever
install:
  - npm i .
script:
  - npm run eslint
  - npm run cover
  - npm run codeclimate_cov
  - npm run semantic-release
