---
branches:
  only:
    - master
    - yml
language: node_js
node_js:
  - "6.9.2"
sudo: required
cache:
  directories:
    - node_modules
before_install:
  - npm config set spin false
install:
  - npm i koaton-exporter
script:
  - npm run export
  - ls lib -a
