---
language: node_js
node_js:
  - "4.4.4"
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
cache:
  directories:
    - node_modules

before_install:
  - npm install -g bower
  - npm install -g forever
  - npm install -g ember
  - "npm config set spin false"

install:
  - npm install . -g
  - mkdir secondtest
  - cd secondtest
  - koaton new testapp
  - cd testapp
  - koaton ember restapp -nf

script:
  - npm test
