---
branches:
  only:
    - master
services:
  - mongodb
language: node_js
node_js:
  - "6.9.2"
sudo: true
addons:
  hosts:
    - www.koaton.test
    - koaton.test
    - koaton.t3st
    - origin.koaton.test
  apt:
    packages:
    - nginx
cache:
  directories:
    - node_modules
before_install:
  - npm config set spin false
  - npm install -g ember-cli@2.9.1
install:
  - git clone https://github.com/gerard2p/koaton-demoapp.git testingapp
  - cd testingapp
  - npm i --only=prod
  - cd ..
  - npm i .
script:
  - npm run eslint
  - npm run cover
  - npm run codeclimate_cov
  - npm run semantic-release
