---
language: node_js
node_js:
  - "4.4.4"
sudo: false

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"

install:
  - npm install
  - npm link

script:
  - npm test
