---
branches:
  only:
    - master
    - yml
services:
  - mongodb
language: node_js
node_js:
  - "6.9.2"
sudo: required
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - nginx
  hosts:
    - www.koaton.test
    - koaton.test
    - koaton.t3st
    - origin.koaton.test
cache:
  directories:
    - node_modules
before_install:
  - npm config set spin false
  - npm install -g codeclimate-test-reporter
install:
  - npm i koaton-exporter
script:
  - npm run export
  - ls lib -a
  - ls lib/src -a
